name: CI/CD for NomadChef backend services

on:
  push:
    branches:
      - authService
      - main
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend  # Set default for all steps

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Verify directory structure
      run: |
        echo "Current directory: $(pwd)"
        ls -la
        ls -la ./backend  # Verify backend directory exists

    - name: Set up Node.js
      uses: actions/setup-node@v4  # No working-directory needed now
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci  # Inherits default working-directory

    - name: Build
      working-directory: ./backend
      run: npm run build
    
    - name: Prepare for production
      working-directory: ./backend
      run: npm prune --production

    - name: Create deployment package
      run: |
        cd backend
        cp -r node_modules dist/  # Include production dependencies
        cd dist
        zip -r ../../function.zip . -x "*.git*"  # Exclude unnecessary files
        cd ../..
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Deploy lambda function
      working-directory: ./backend
      run: |
        aws lambda update-function-code --function-name ${{ secrets.AUTH_SERVICE_ARN }} --zip-file fileb://../function.zip
